import { plural } from '../lib/format.ts'

export const strings = {
  appName: 'Chess Agent',
  close: 'Close',

  welcome: {
    eyebrow: 'Personal game analysis agent · everything stays local',
    title: 'Talk to your games.',
    lede: 'Import your Lichess game archive. The agent finds patterns, digs into the causes of mistakes, and shows them on charts — no manual engine-graph spelunking.',
    dropTitle: 'Drop a PGN archive here',
    dropOr: 'or',
    dropPick: 'choose a file',
    orLichess: 'or fetch directly from Lichess',
    nickPlaceholder: 'your Lichess username',
    fetch: 'Fetch from Lichess',
    previewTitle: 'Found your games',
    previewStats: (d: { count: number; from: string; to: string }) =>
      `${d.count} ${plural(d.count, ['game', 'games', 'games'])} · ${d.from} — ${d.to}`,
    previewBreakdown: (parts: { speed: string; count: number }[]) =>
      parts.map((p) => `${p.speed}: ${p.count}`).join(' · '),
    importRecent: 'Import these',
    importHalfYear: 'Past half-year',
    importAll: 'Everything',
    fetching: 'Fetching from Lichess',
    fetched: (count: number) => `Fetched ${count} ${plural(count, ['game', 'games', 'games'])}…`,
    fetchingHint: 'Lichess serves about 20 games per second. A large archive takes a minute or two.',
    cancel: 'Cancel',
    noNick: 'Enter your Lichess username first.',
    howTo: 'How to download your Lichess game archive',
    askNick: 'Your Lichess username — this opens the game export page',
    reading: 'Reading file…',
    importing: 'Parsing games',
    importingHint: 'No need to wait: parsing runs in the background and leaves saved games alone.',
    whoAreYou: (name: string) => `Are you ${name}?`,
    whoAreYouHint: 'The username tells us which color you played and who won.',
    yes: "Yes, that's me",
    otherName: 'Different username',
    nothingImported: 'No new games',
    imported: (count: number) => `Imported ${count}`,
    importAgain: 'Import another file',
    stats: (d: { imported: number; duplicates: number; skipped: number }) =>
      `Added ${d.imported} · already had ${d.duplicates} · skipped ${d.skipped}`,
    skippedHint: 'Non-standard variants, unfinished games, and games without your username are skipped.',
    notPgn: 'Does not look like a PGN archive: found no games.',
    failed: 'Import failed',
    retry: 'Try again',
    privacy: 'Games stay in this browser only. Only the fragments needed for the answer are sent to models via OpenRouter.',
    chipsLabel: 'After import you can ask',
    chips: [
      'Fetch recent games from Lichess',
      'Analyze my level of play',
      'What should I focus on?',
    ],
  },

  sidebar: {
    newChat: 'New chat',
    recent: 'Recent',
    library: 'Library',
    importMore: 'Import more',
    updateFromLichess: 'Update from Lichess',
    background: 'Background analysis',
    backgroundOf: (done: number, total: number) => `${done} of ${total}`,
    backgroundPause: 'Pause',
    backgroundResume: 'Resume',
    withAnalysis: 'analyzed',
    localOnly: 'Stored on this device only',
  },

  settings: {
    title: 'Settings',
    key: 'OpenRouter key',
    keyPlaceholder: 'sk-or-…',
    keyHint:
      'The key lives in this browser only and is sent to a single recipient — openrouter.ai, together with the model request.',
    keyLink: 'Get a key at openrouter.ai',
    model: 'Model',
    modelHint: 'Only models that support tool calls are shown — the agent cannot work without them.',
    modelFilter: 'Filter…',
    loadModels: 'Load list',
    loadingModels: 'Loading…',
    noKeyForModels: 'Paste the key first',
    check: 'Check',
    checking: 'Checking…',
    checkOk: 'Key and model work',
    depth: 'Analysis depth',
    depthHint: 'Higher depth means more accurate evals and longer compute. Analysis runs on your device.',
    background: 'Background analysis',
    backgroundOff: 'off',
    backgroundLast: (count: number) => `last ${count}`,
    backgroundHint:
      'Recent games are analyzed on their own while you are away: analysis yields to the agent reply and pauses.',
    count: 'How many recent games to analyze',
    analyze: 'Analyze',
    analyzing: 'Analyzing…',
    done: (d: { analyzed: number; skipped: number; mistakesFound: number }) =>
      `Analyzed ${d.analyzed}, skipped ${d.skipped}, mistakes found ${d.mistakesFound}`,
    cancelled: 'Analysis cancelled',
    failed: 'Analysis failed',
    nothingToAnalyze: 'Nothing to analyze: the library is empty',
    danger: 'Danger zone',
    clearLibrary: 'Clear library',
    clearChats: 'Clear chats',
    clearLibraryConfirm: (count: number) =>
      `Delete all games (${count}) and their analyses? This cannot be undone — you will need to re-import the archive.`,
    clearChatsConfirm: (count: number) => `Delete all chats (${count})? This cannot be undone.`,
    cleared: 'Deleted',
  },

  analysis: {
    label: 'Analysis',
    positions: (done: number, total: number) => `${done}/${total} positions`,
    ofGames: (done: number, total: number) => `game ${done + 1} of ${total}`,
    cancel: 'Cancel',
  },

  chat: {
    model: 'Model',
    pickModel: '[select]',
    you: 'You',
    agent: 'Agent',
    placeholder: 'Ask about your games…',
    newChatTitle: 'New chat',
    thinking: 'Thinking…',
    statusThinking: 'Thinking',
    statusWriting: 'Writing answer',
    statusTools: 'Checking games',
    statusAnalyzing: 'Analyzing with engine',
    statusStep: (round: number) => `step ${round}`,
    stop: 'Stop',
    retry: 'Retry',
    traceDone: 'done',
    traceError: 'error',
    deleteChat: 'Delete chat',
    emptyTitle: 'What shall we ask?',
    emptyHint: 'The agent answers only from your games and shows what each conclusion is based on.',
    starters: [
      { label: 'Fetch recent games', kind: 'import', text: '' },
      { label: 'My level of play', kind: 'send', text: 'Analyze my current level of play' },
      {
        label: 'What to focus on?',
        kind: 'send',
        text: 'What problem should I focus on right now?',
      },
    ],
    noEvalsHint:
      'No game has been engine-analyzed yet: the agent cannot answer about mistakes and eval loss. Analysis runs on your device.',
    noEvalsAction: 'Analyze games',
    menu: 'Menu',
    send: 'Send',
    traceArgs: 'Request',
    traceResult: 'Tool response',
    traceRunning: 'running…',
  },

  genui: {
    blockFailed: 'Block failed to render',
    blockBuilding: 'Building block…',
  },
} as const
